# Generated by Django 5.0.1 on 2024-01-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('IM', 'Import'), ('EX', 'Export'), ('SVR', 'Server'), ('Bok', 'Bookkeeping')], max_length=5)),
                ('description', models.CharField(max_length=256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.user')),
            ],
        ),
    ]
