# Generated by Django 4.2.7 on 2024-01-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_task_tasktest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTest',
            new_name='Task',
        ),
    ]
