# Generated by Django 5.0.1 on 2024-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.CharField(choices=[('Adam', 'Adam'), ('Yossi', 'Yossi'), ('Nati', 'Nati'), ('Daniel', 'Daniel')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
