# Generated by Django 4.2.7 on 2024-01-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_client_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Import', 'Import'), ('Export', 'Export'), ('Server', 'Server'), ('Bookkeeping', 'Bookkeeping')], max_length=30),
        ),
    ]
