# Generated by Django 4.2.7 on 2024-02-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.CharField(choices=[('United ', 'United '), ('Sky', 'Sky'), ('World Courier', 'World Courier'), ('Krief', 'Krief')], max_length=15),
        ),
    ]
