# Generated by Django 4.2.7 on 2024-02-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.user')),
            ],
        ),
    ]
