# Generated by Django 3.2.21 on 2024-02-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_sharedtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='sharedtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Import', 'Import'), ('Export', 'Eport'), ('Server', 'Server'), ('Bookkeeping', 'Bookkeeping')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.CharField(choices=[('United', 'United'), ('Sky', 'Sky'), ('World Courier', 'Worldcourier'), ('Krief', 'Krief')], max_length=15),
        ),
    ]
